# Generated by Django 5.2 on 2025-05-09 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_product_description_product_tags_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='last_updated',
        ),
    ]
